### ISSUE TITLE
Project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio-java#1]
Documentations should be rewritten and cleaned up to adapt to the new project setup like the [Nord](https://github.com/arcticicestudio/nord) project.

**Tasks**
  - [x] Rewrite the `.gitignore` file
  - [x] Delete overhead and old project files
  - [x] Update all documentations to the new style and layout
  - [x] Move to the Apache 2.0 license
  - [x] Add new project branding assets
  - [x] Refactor the Travis CI configuration dotfile
